#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

rice_dir="$HOME/.config/bspwm/walls/"

pkill conky
pkill polybar

INTERNAL_MONITOR="DP-1"
	EXTERNAL_MONITOR="HDMI-1"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
	fi

bspc config external_rules_command "$HOME"/.config/bspwm/scripts/ExternalRules

bspc config window_gap					6
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle			false
bspc config gapless_monocle				false

bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

bspc rule -a scratch sticky=on state=floating focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }

feh --bg-fill ${rice_dir}
#-z --no-fehbg  for random wallaper

pidof -q eww || { eww -c "$HOME"/.config/bspwm/eww daemon & }

sxhkd -c ~/.config/bspwm/sxhkdrc > /dev/null 2> /dev/null&
polybar example -c ~/.config/polybar/config.ini &

conky -c $HOME/.config/conky/ConkyWidgets/conky-widgets &
# conky -c $HOME/.config/conky/Alterf/Alterf.conf &> /dev/null &

udiskie &
