#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


  
		bspc monitor -d '1' '2' '3' '4' '5' '6'
	


bspc config window_gap					6
bspc config split_ratio					0.51
bspc config single_monocle				true
bspc config borderless_monocle			false
bspc config gapless_monocle				false

bspc config focus_follows_pointer		true
bspc config pointer_follows_focus		false
bspc config pointer_motion_interval		5
bspc config pointer_modifier			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config pointer_action3				resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }

sxhkd -c ~/.config/bspwm/sxhkdrc > /dev/null 2> /dev/null 2> ~/errors&
polybar example -c ~/.config/polybar/config.ini &
